#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  9 14:28:43 2019

@author: miko
"""

import numpy as np


def concat(sorcedoc,summarydoc,savedocname):
    sourcef=open(sorcedoc,'r') 
    source_lines=sourcef.readlines()
    sourcef.close()
    
    summaryf=open(summarydoc,'r') 
    summary_lines=summaryf.readlines()
    summaryf.close()
    
    f = open(savedocname,'w')
    for i in range(len(source_lines)):
        temp=summary_lines[i].replace("\n","")
        print(len(source_lines[i]),'length',len(summary_lines[i]))
        f.write(temp+' <token> '+source_lines[i])
    f.close()

    
if __name__ == '__main__':
    concat('/home/miko/myexp/transformer/data/src-train_word.txt','/home/miko/myexp/train_sensummary_1.txt','newconcat/sent1_train_concat_data.txt')
    concat('/home/miko/myexp/transformer/data/src-val_word.txt','/home/miko/myexp/val_sensummary_1.txt','newconcat/sent1_val_concat_data.txt')
    concat('/home/miko/myexp/transformer/data/src-test_word.txt','/home/miko/myexp/test_sensummary_1.txt','newconcat/sent1_test_concat_data.txt')
    
    concat('/home/miko/myexp/transformer/data/src-train_word.txt','/home/miko/myexp/train_sensummary_3.txt','newconcat/sent3_train_concat_data.txt')
    concat('/home/miko/myexp/transformer/data/src-val_word.txt','/home/miko/myexp/val_sensummary_3.txt','newconcat/sent3_val_concat_data.txt')
    concat('/home/miko/myexp/transformer/data/src-test_word.txt','/home/miko/myexp/test_sensummary_3.txt','newconcat/sent3_test_concat_data.txt')
    
    concat('/home/miko/myexp/transformer/data/src-train_word.txt','/home/miko/myexp/train_textsummary_9.txt','newconcat/text9_train_concat_data.txt')
    concat('/home/miko/myexp/transformer/data/src-val_word.txt','/home/miko/myexp/val_textsummary_9.txt','newconcat/text9_val_concat_data.txt')
    concat('/home/miko/myexp/transformer/data/src-test_word.txt','/home/miko/myexp/test_textsummary_9.txt','newconcat/text9_test_concat_data.txt')
   
    concat('/home/miko/myexp/transformer/data/src-train_word.txt','/home/miko/myexp/train_textsummary_11.txt','newconcat/text11_train_concat_data.txt')
    concat('/home/miko/myexp/transformer/data/src-val_word.txt','/home/miko/myexp/val_textsummary_11.txt','newconcat/text11_val_concat_data.txt')
    concat('/home/miko/myexp/transformer/data/src-test_word.txt','/home/miko/myexp/test_textsummary_11.txt','newconcat/text11_test_concat_data.txt')